<?php

namespace Proxies\__CG__\sosFSO\HrBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Situation extends \sosFSO\HrBundle\Entity\Situation implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setEchelon($echelon)
    {
        $this->__load();
        return parent::setEchelon($echelon);
    }

    public function getEchelon()
    {
        $this->__load();
        return parent::getEchelon();
    }

    public function setNumeroInference($numeroInference)
    {
        $this->__load();
        return parent::setNumeroInference($numeroInference);
    }

    public function getNumeroInference()
    {
        $this->__load();
        return parent::getNumeroInference();
    }

    public function setDateEffets($dateEffets)
    {
        $this->__load();
        return parent::setDateEffets($dateEffets);
    }

    public function getDateEffets()
    {
        $this->__load();
        return parent::getDateEffets();
    }

    public function setAnciennete($anciennete)
    {
        $this->__load();
        return parent::setAnciennete($anciennete);
    }

    public function getAnciennete()
    {
        $this->__load();
        return parent::getAnciennete();
    }

    public function setPersonne(\sosFSO\HrBundle\Entity\Personne $personne = NULL)
    {
        $this->__load();
        return parent::setPersonne($personne);
    }

    public function getPersonne()
    {
        $this->__load();
        return parent::getPersonne();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function setRemarques($remarques)
    {
        $this->__load();
        return parent::setRemarques($remarques);
    }

    public function getRemarques()
    {
        $this->__load();
        return parent::getRemarques();
    }

    public function setCadre(\sosFSO\HrBundle\Entity\Cadre $cadre = NULL)
    {
        $this->__load();
        return parent::setCadre($cadre);
    }

    public function getCadre()
    {
        $this->__load();
        return parent::getCadre();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'echelon', 'numeroInference', 'dateEffets', 'remarques', 'cadre');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}