<?php

namespace Proxies\__CG__\sosFSO\GRHBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Personne extends \sosFSO\GRHBundle\Entity\Personne implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setNom($nom)
    {
        $this->__load();
        return parent::setNom($nom);
    }

    public function getNom()
    {
        $this->__load();
        return parent::getNom();
    }

    public function setPrenom($prenom)
    {
        $this->__load();
        return parent::setPrenom($prenom);
    }

    public function getPrenom()
    {
        $this->__load();
        return parent::getPrenom();
    }

    public function setNomAr($nomAr)
    {
        $this->__load();
        return parent::setNomAr($nomAr);
    }

    public function getNomAr()
    {
        $this->__load();
        return parent::getNomAr();
    }

    public function setPrenomAr($prenomAr)
    {
        $this->__load();
        return parent::setPrenomAr($prenomAr);
    }

    public function getPrenomAr()
    {
        $this->__load();
        return parent::getPrenomAr();
    }

    public function setCin($cin)
    {
        $this->__load();
        return parent::setCin($cin);
    }

    public function getCin()
    {
        $this->__load();
        return parent::getCin();
    }

    public function setSom($som)
    {
        $this->__load();
        return parent::setSom($som);
    }

    public function getSom()
    {
        $this->__load();
        return parent::getSom();
    }

    public function setPosteBudgetaire($posteBudgetaire)
    {
        $this->__load();
        return parent::setPosteBudgetaire($posteBudgetaire);
    }

    public function getPosteBudgetaire()
    {
        $this->__load();
        return parent::getPosteBudgetaire();
    }

    public function setDateNaissance($dateNaissance)
    {
        $this->__load();
        return parent::setDateNaissance($dateNaissance);
    }

    public function getDateNaissance()
    {
        $this->__load();
        return parent::getDateNaissance();
    }

    public function setLieuNaissance($lieuNaissance)
    {
        $this->__load();
        return parent::setLieuNaissance($lieuNaissance);
    }

    public function getLieuNaissance()
    {
        $this->__load();
        return parent::getLieuNaissance();
    }

    public function setEtatMatrimonial($etatMatrimonial)
    {
        $this->__load();
        return parent::setEtatMatrimonial($etatMatrimonial);
    }

    public function getEtatMatrimonial()
    {
        $this->__load();
        return parent::getEtatMatrimonial();
    }

    public function setSexe($sexe)
    {
        $this->__load();
        return parent::setSexe($sexe);
    }

    public function getSexe()
    {
        $this->__load();
        return parent::getSexe();
    }

    public function setNbEnfants($nbEnfants)
    {
        $this->__load();
        return parent::setNbEnfants($nbEnfants);
    }

    public function getNbEnfants()
    {
        $this->__load();
        return parent::getNbEnfants();
    }

    public function setAdresse($adresse)
    {
        $this->__load();
        return parent::setAdresse($adresse);
    }

    public function getAdresse()
    {
        $this->__load();
        return parent::getAdresse();
    }

    public function setNumTelephonne($numTelephonne)
    {
        $this->__load();
        return parent::setNumTelephonne($numTelephonne);
    }

    public function getNumTelephonne()
    {
        $this->__load();
        return parent::getNumTelephonne();
    }

    public function setDateRecrutement($dateRecrutement)
    {
        $this->__load();
        return parent::setDateRecrutement($dateRecrutement);
    }

    public function getDateRecrutement()
    {
        $this->__load();
        return parent::getDateRecrutement();
    }

    public function setPhoto($photo)
    {
        $this->__load();
        return parent::setPhoto($photo);
    }

    public function getPhoto()
    {
        $this->__load();
        return parent::getPhoto();
    }

    public function addDiplome(\sosFSO\GRHBundle\Entity\Diplome $diplomes)
    {
        $this->__load();
        return parent::addDiplome($diplomes);
    }

    public function removeDiplome(\sosFSO\GRHBundle\Entity\Diplome $diplomes)
    {
        $this->__load();
        return parent::removeDiplome($diplomes);
    }

    public function getDiplomes()
    {
        $this->__load();
        return parent::getDiplomes();
    }

    public function addSituation(\sosFSO\GRHBundle\Entity\Situation $situations)
    {
        $this->__load();
        return parent::addSituation($situations);
    }

    public function removeSituation(\sosFSO\GRHBundle\Entity\Situation $situations)
    {
        $this->__load();
        return parent::removeSituation($situations);
    }

    public function getSituations()
    {
        $this->__load();
        return parent::getSituations();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'nom', 'prenom', 'nomAr', 'prenomAr', 'cin', 'som', 'posteBudgetaire', 'dateNaissance', 'lieuNaissance', 'etatMatrimonial', 'sexe', 'nbEnfants', 'adresse', 'numTelephonne', 'dateRecrutement', 'photo', 'diplomes', 'situations');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}