<?php

namespace Proxies\__CG__\sosFSO\GRHBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Affectation extends \sosFSO\GRHBundle\Entity\Affectation implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setDateAffectation($dateAffectation)
    {
        $this->__load();
        return parent::setDateAffectation($dateAffectation);
    }

    public function getDateAffectation()
    {
        $this->__load();
        return parent::getDateAffectation();
    }

    public function setPoste($poste)
    {
        $this->__load();
        return parent::setPoste($poste);
    }

    public function getPoste()
    {
        $this->__load();
        return parent::getPoste();
    }

    public function setDateDetachement($dateDetachement)
    {
        $this->__load();
        return parent::setDateDetachement($dateDetachement);
    }

    public function getDateDetachement()
    {
        $this->__load();
        return parent::getDateDetachement();
    }

    public function setRemarques($remarques)
    {
        $this->__load();
        return parent::setRemarques($remarques);
    }

    public function getRemarques()
    {
        $this->__load();
        return parent::getRemarques();
    }

    public function setService(\sosFSO\GRHBundle\Entity\Service $service = NULL)
    {
        $this->__load();
        return parent::setService($service);
    }

    public function getService()
    {
        $this->__load();
        return parent::getService();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'dateAffectation', 'poste', 'dateDetachement', 'remarques', 'service');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}