<?php

namespace sosFSO\GRHBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class CadreController__JMSInjector
{
    public static function inject($container) {
        $instance = new \sosFSO\GRHBundle\Controller\CadreController();
        return $instance;
    }
}
